import {createProgressStore, PROGRESS_PREFIX} from './progress.js';
import {createReadingTracker} from './reading-progress.js';
import {resumeBanner, showProgress} from './progress-view.js';
import {renderLab, relatedLabLinks, labs} from './labs.js?v=20261006-feedback';
import {interpretationHref, interpretationIndex, showInterpretation, interpretationBanner, markHistoricalPage} from './interpretations.js?v=20261006-condensed';
const $ = (s, root=document) => root.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rich = s => esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
let progress,reading,storageWarning=false;
let state={done:new Set(),weak:new Set()};
function storageProblem(){document.querySelectorAll('[data-saved-label]').forEach(node=>node.textContent='未能保存 · 请导出备份');if(!storageWarning){storageWarning=true;toast('浏览器未允许保存进度，请到“学习进度”导出备份。')}}
function setMark(k,status){state=progress.setMark(k,status)}
const savedLabel=()=>progress?.isAvailable()?'进度自动保存 · 备份与恢复':'未能保存 · 请导出备份';
let decks=[],cache={},sources=null,routeVersion=0,activeDeck=null,activePage=0,allPromise;
let disposeLab=()=>{};
const main=$('#main'),side=$('#sidebar');
const labels={core:'核心理解',support:'补充理解',skim:'背景速览',admin:'课程安排'};
const resource={html:['HTML 元素参考','https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements'],css:['CSS 层叠与优先级','https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascade/Cascade'],jsbasics:['JavaScript Guide','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide'],jsadvanced:['JavaScript Guide','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide'],json:['JSON 格式标准','https://www.rfc-editor.org/rfc/rfc8259'],python:['Python 官方教程','https://docs.python.org/3/tutorial/'],dom:['DOM 官方概述','https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model'],forms:['HTML 表单','https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms'],http:['HTTP 概述','https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview'],web:['URL API','https://developer.mozilla.org/en-US/docs/Web/API/URL'],vibe:['JavaScript 错误处理','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling'],ai:['NASA 航天器热控制','https://www.nasa.gov/smallsat-institute/sst-soa/thermal-control/']};
const href=(id,page=1)=>`#/deck/${id}/${page}`;
const key=(id,p)=>`${id}:${p}`;
const pct=d=>Math.round([...state.done].filter(k=>k.startsWith(d.id+':')).length/d.count*100);
const pill=p=>`<span class="pill ${esc(p)}">${labels[p]||'复习'}</span>`;
async function fetchJSON(path){const r=await fetch(path);if(!r.ok)throw new Error(`无法载入 ${path} (${r.status})`);return r.json()}
async function loadDeck(id){return cache[id]??(cache[id]=await fetchJSON(`content/${id}.json`))}
async function loadAll(){return allPromise??(allPromise=Promise.all(decks.map(d=>loadDeck(d.id))).catch(error=>{allPromise=null;throw error}))}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2500)}
function navBase(active){return `<nav class="side-nav"><a href="#/interpretations" class="${active==='interpretations'?'active':''}"><span class="nav-icon">≡</span>整体总结</a><a href="#/" class="${active==='home'?'active':''}"><span class="nav-icon">▤</span>课程目录</a><a href="#/review" class="${active==='review'?'active':''}"><span class="nav-icon">◇</span>重点与待复习</a><a href="#/quiz" class="${active==='quiz'?'active':''}"><span class="nav-icon">?</span>自测练习</a><a href="#/lab" class="${active==='lab'?'active':''}"><span class="nav-icon">⌘</span>交互实验室</a><a href="#/progress" class="${active==='progress'?'active':''}"><span class="nav-icon">✓</span>学习进度</a></nav>`}
function sidebar(active='home',deck=null,pages=[],page=0){
 if(deck){side.innerHTML=`<a href="#/" class="side-back">‹ 返回课程目录</a><a href="${interpretationHref(deck.id)}" class="side-summary-link">本讲整体总结与串讲 →</a><label class="side-heading" for="course-select">切换讲义</label><select id="course-select" class="course-select">${decks.map(d=>`<option value="${d.id}" ${d.id===deck.id?'selected':''}>${esc(d.title)} · ${d.count} 页</option>`).join('')}</select><div class="side-progress" style="margin:0;padding:10px 8px">本讲已掌握 ${pct(deck)}%<div class="progress"><i style="width:${pct(deck)}%"></i></div><a class="save-status" href="#/progress" data-saved-label>${savedLabel()}</a></div><nav class="nav-pages" aria-label="逐页目录">${pages.map((p,i)=>`${i===0||p.section!==pages[i-1].section?`<div class="section-label">${esc(p.section)}</div>`:''}<a href="${href(deck.id,p.page)}" class="page-nav ${page===p.page?'active':''} ${state.done.has(key(deck.id,p.page))?'done':''}" ${page===p.page?'aria-current="page"':''}><span class="num">${state.done.has(key(deck.id,p.page))?'✓':String(p.page).padStart(2,'0')}</span><span>${esc(p.title)}</span></a>`).join('')}</nav>`;
 $('#course-select').addEventListener('change',e=>location.hash=href(e.target.value));
 const item=$('.page-nav.active',side);if(item)side.scrollTop=Math.max(0,item.offsetTop-side.clientHeight/2);
 }else{side.innerHTML=navBase(active)+`<div class="side-heading">讲义 · LECTURES</div>${decks.map((d,i)=>`<a class="deck-nav" href="${href(d.id,d.id==='web'?51:1)}"><span class="deck-num">${String(i+1).padStart(2,'0')}</span><span>${esc(d.title)}</span><small>${d.count}</small></a>`).join('')}<div class="side-progress">总体掌握进度 <strong>${state.done.size} / 816</strong><div class="progress"><i style="width:${state.done.size/816*100}%"></i></div><a class="save-status" href="#/progress" data-saved-label>${savedLabel()}</a></div>`}
}
function home(){sidebar();activeDeck=null;document.title='CSCI 571 · Midterm 复习手册';
 const last=progress.lastReading();const continueHref=last?.route||href('web',51);
 main.innerHTML=`<div class="breadcrumb">CSCI 571 <span>/</span> Fall 2026 <span>/</span> Exam 01</div><section class="home-head"><div><span class="eyebrow">THE STUDY EDITION</span><h1>Midterm 复习手册</h1><p>逐页理解课件，读懂代码，再用问题检验自己。</p></div><div class="edition">01<small>WEB TECHNOLOGIES</small></div></section><section class="overview-strip"><div><small>下一段复习</small><a class="resume" href="${continueHref}">${last?'继续 '+esc(last.title):'从 Web 核心概念开始'} <span>›</span></a></div><div><small>讲义覆盖</small><strong>806<span>页 / 13 份讲义</span></strong></div><div><small>已掌握</small><strong>${state.done.size}<span>/ 816 页（含 syllabus）</span></strong></div></section><section class="interpretation-home-entry"><div><span class="eyebrow">SLIDES INTERPRETATION</span><h2>先把每一讲连起来理解</h2><p>每份课件精简为关键规则、易错点与必要示例。保留全页对照，发展历史按教授说明跳过。</p></div><a href="#/interpretations">阅读整体总结 →</a></section><div class="section-top"><div><h2>课程目录</h2><p>按教学顺序阅读，或直接进入需要巩固的部分。</p></div><a class="pill" href="#/review">查看重点</a></div><div class="course-grid">${decks.map((d,i)=>`<div class="course-card"><a class="course-main-link" href="${href(d.id,d.id==='web'?51:1)}"><div class="card-line"><span class="course-index">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(d.title)}</h3><p>${esc(d.description)}</p></div></div><div class="course-meta"><span>${esc(d.file)}</span><span>${d.count} 页 · 已掌握 ${pct(d)}%</span></div><div class="progress"><i style="width:${pct(d)}%"></i></div></a><div class="course-reading-links"><a href="${interpretationHref(d.id)}">整体总结与串讲 →</a><a href="${href(d.id,d.id==='web'?51:1)}">逐页阅读</a></div></div>`).join('')}</div><div class="notice"><strong>复习范围依据</strong><br>Exam #1：10月6日 17:00，60分钟，占总成绩40%；理论与代码分析，不要求写代码。Web Basics 从 PDF 第51页起标记为考试相关内容。AI Basics 的完整考试范围待教师确认；本站保留全部逐页讲解。重点标签用于安排学习，不代表预测分值。</div><footer>中文讲解与原创示例 · 原页对照 · 少量官方补充资料<br>页码采用 PDF 阅读器页序号，可能与幻灯片页脚编号不同。课程安排以教师最新通知为准。</footer>`;
}
function sourcePanel(deck,p){return `<aside class="source-panel"><div class="source-head"><span>原始幻灯片</span><span>PDF ${p.page} / ${deck.count}</span></div><button class="source-image-button" data-image="assets/slides/${deck.id}/${String(p.page).padStart(3,'0')}.jpg" aria-label="放大第${p.page}页原始幻灯片"><img src="assets/slides/${deck.id}/${String(p.page).padStart(3,'0')}.jpg" alt="${esc(deck.title)} 第${p.page}页：${esc(p.title)}" loading="lazy" width="1440" height="1080"></button><div class="source-caption">${esc(deck.file)}<br>点击图片放大；此处页码为 PDF 页序。</div><details class="raw-source" data-deck="${deck.id}" data-page="${p.page}"><summary>查看本页原文</summary><pre class="source-text">展开后载入…</pre></details><div class="reading-hint">阅读顺序：先理解本页，独立回答自测，再核对答案。代码示例可能是为讲解改写的版本。</div>${(p.links?.length?p.links:resource[deck.id]?[{label:resource[deck.id][0],url:resource[deck.id][1]}]:[]).map(l=>`<a class="external" href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">补充阅读 · ${esc(l.label)} ↗</a>`).join('')}</aside>`}
const diagramMap={'web:53':'request','http:25':'request','css:39':'box','dom:5':'dom','json:32':'origin','forms:38':'request','ai:34':'software','vibe:5':'cycle'};
async function reader(id,page,version){const d=decks.find(d=>d.id===id);if(!d)throw new Error('没有找到这份讲义。');const pages=await loadDeck(id);if(version!==routeVersion)return;page=Math.min(d.count,Math.max(1,Number(page)||1));const p=pages.find(x=>x.page===page);if(!p)throw new Error('这一页暂时无法载入。');activeDeck=id;activePage=page;sidebar('reader',d,pages,page);document.title=`${p.title} · ${d.title} P${page} · CSCI 571`;
 const example=p.example;const diagram=diagramMap[key(id,page)];
 main.innerHTML=`<div class="breadcrumb"><a href="#/">课程目录</a><span>/</span><span>${esc(d.title)}</span><span>/</span>PDF ${page}</div><header class="reader-top"><div><div class="reader-meta"><span>${esc(p.section)}</span><span class="divider">/</span>${pill(p.priority)}${id==='web'&&page<51?'<span>本讲考试标记之前</span>':''}${id==='ai'?'<span>考试范围待确认</span>':''}</div><h1>${esc(p.title)}</h1></div><div class="page-number">${String(page).padStart(2,'0')}<span> / ${d.count}</span></div></header>${interpretationBanner(id)}<div class="reader-layout"><article class="lesson"><p class="lead">${rich(p.summary)}</p><details class="mobile-source"><summary>对照本页原始幻灯片</summary>${sourcePanel(d,p)}</details><div class="lesson-body">${p.explanation.map(t=>`<p>${rich(t)}</p>`).join('')}</div>${diagram?`<img class="diagram" src="assets/diagrams/${diagram}.svg" alt="${({request:'浏览器请求与服务器响应的关系',box:'盒模型的内容、内边距、边框与外边距',dom:'DOM节点树',origin:'同源判断的三部分',software:'Software 1.0、2.0、3.0比较',cycle:'提示、生成、测试、观察、修正的循环'})[diagram]}">`:''}<section class="takeaways"><span class="block-label">这一页要记住</span><ul>${p.takeaways.map(t=>`<li>${rich(t)}</li>`).join('')}</ul></section>${p.pitfall?`<aside class="pitfall"><span class="block-label">易错点 / 课件澄清</span>${rich(p.pitfall)}</aside>`:''}${example?`<h2>用例子理解</h2><div class="code-box"><div class="code-toolbar"><span>${esc(example.lang).toUpperCase()} · 示例</span><button id="copy-code">复制代码</button></div><pre><code>${esc(example.code)}</code></pre></div><p class="example-note">${rich(example.explanation||'')}</p>${example.lang==='html'?'<button id="preview-code" class="print-button">查看 HTML 示例效果</button><div id="preview-slot"></div>':''}`:''}${relatedLabLinks(id,page)}${p.question?`<section class="quiz-block"><span class="block-label">停一下，检查理解</span><p>${rich(p.question.prompt)}</p><details><summary>展开答案与解释</summary><div class="answer">${rich(p.question.answer)}</div></details></section>`:''}<div class="reader-actions"><button id="mark-done" class="${state.done.has(key(id,page))?'soft-button':'primary'}">${state.done.has(key(id,page))?'✓ 已掌握':'标记已掌握'}</button><button id="mark-weak" class="${state.weak.has(key(id,page))?'soft-button':''}">${state.weak.has(key(id,page))?'◇ 已加入待复习':'加入待复习'}</button><button id="print-page">打印本页</button></div><nav class="pager" aria-label="前后页">${page>1?`<a href="${href(id,page-1)}"><small>PREVIOUS · ${page-1}</small>${esc(pages[page-2]?.title||'上一页')}</a>`:'<span></span>'}${page<d.count?`<a href="${href(id,page+1)}"><small>NEXT · ${page+1}</small>${esc(pages[page]?.title||'下一页')}</a>`:`<a href="#/">本讲阅读结束 · 返回目录</a>`}</nav><footer>可使用键盘 ← / → 翻页。进度保存到当前浏览器，不会上传。</footer></article>${sourcePanel(d,p)}</div>`;
 markHistoricalPage(id,page,{main,isCurrent:()=>version===routeVersion});
 document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>{$('#large-image').src=b.dataset.image;$('#image-dialog').showModal()}));
 document.querySelectorAll('.raw-source').forEach(el=>el.addEventListener('toggle',async()=>{if(!el.open)return;try{sources??=await fetchJSON('content/sources.json');$('.source-text',el).textContent=sources[id]?.[page-1]?.text||'此页主要为图片，请查看原图。'}catch{$('.source-text',el).textContent='原文载入失败，可查看原图。'}}));
 $('#mark-done').onclick=()=>{const k=key(id,page),wasDone=state.done.has(k);setMark(k,wasDone?'none':'done');if(!wasDone&&page<d.count){$('#mark-done').disabled=true;location.hash=href(id,page+1);toast('已标记掌握，进入下一页')}else{refreshMarkButtons(id,page,d);if(!wasDone)toast('已标记掌握；本讲已到最后一页')}};
 $('#mark-weak').onclick=()=>{const k=key(id,page);setMark(k,state.weak.has(k)?'none':'weak');refreshMarkButtons(id,page,d)};
 $('#print-page').onclick=()=>window.print();
 if(example){$('#copy-code').onclick=async()=>{try{await navigator.clipboard.writeText(example.code);toast('代码已复制')}catch{toast('浏览器未允许复制，请在代码块中选取。')}};if($('#preview-code'))$('#preview-code').onclick=()=>{const f=document.createElement('iframe');f.className='preview-frame';f.title='HTML代码示例预览';f.setAttribute('sandbox','');f.srcdoc='<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>body{font-family:sans-serif;padding:12px}</style>'+example.code;$('#preview-slot').replaceChildren(f);toast('预览呈现 HTML/CSS；脚本和表单提交不会执行。')}}
}
function refreshMarkButtons(id,page,d){const k=key(id,page);$('#mark-done').textContent=state.done.has(k)?'✓ 已掌握':'标记已掌握';$('#mark-done').className=state.done.has(k)?'soft-button':'primary';$('#mark-weak').textContent=state.weak.has(k)?'◇ 已加入待复习':'加入待复习';$('#mark-weak').className=state.weak.has(k)?'soft-button':'';sidebar('reader',d,cache[id],page);toast(progress.isAvailable()?'复习进度已保存':'本页进度已更新，但浏览器未允许保存；请导出备份')}
async function review(version){document.title='重点与待复习 · CSCI 571';sidebar('review');activeDeck=null;await loadAll();if(version!==routeVersion)return;main.innerHTML=`<div class="breadcrumb"><a href="#/">课程目录</a><span>/</span>重点与待复习</div><span class="eyebrow">FOCUS YOUR REVIEW</span><h1>把时间留给薄弱处</h1><p class="muted">核心标签表示理解优先级；待复习列表由你在阅读时标记。</p><p class="teacher-scope-update">教授补充：发展历史无需复习或记忆。复习时请结合此说明；<a href="#/interpretations">整体总结中已单独标出可跳过部分 →</a></p><div class="toolbar"><label for="review-mode">查看</label><select id="review-mode"><option value="weak">我的待复习（${state.weak.size}）</option><option value="core" ${state.weak.size?'':'selected'}>核心理解</option><option value="unread">尚未掌握</option><option value="all">全部页面</option></select><label for="review-deck">讲义</label><select id="review-deck"><option value="all">全部讲义</option>${decks.map(d=>`<option value="${d.id}">${esc(d.title)}</option>`).join('')}</select></div><div id="review-list"></div>`;
 function render(){const mode=$('#review-mode').value,deck=$('#review-deck').value;let rows=[];for(const d of decks){if(deck!=='all'&&deck!==d.id)continue;for(const p of cache[d.id]){const k=key(d.id,p.page);if(mode==='weak'&&!state.weak.has(k)||mode==='core'&&p.priority!=='core'||mode==='unread'&&state.done.has(k))continue;rows.push({d,p})}}$('#review-list').innerHTML=`<p class="muted" style="font-size:12px">${rows.length} 页</p>`+(rows.length?rows.map(({d,p})=>`<a class="list-row" href="${href(d.id,p.page)}"><span class="row-page">${String(p.page).padStart(2,'0')}</span><div><h3>${esc(p.title)}</h3><p>${esc(d.title)} · ${esc(p.section)}</p></div>${pill(p.priority)}</a>`).join(''):'<div class="empty">还没有待复习页面。阅读时点击“加入待复习”，就会出现在这里。</div>')}
 $('#review-mode').onchange=render;$('#review-deck').onchange=render;render();
}
async function quiz(version){
 document.title='自测练习 · CSCI 571';sidebar('quiz');activeDeck=null;await loadAll();if(version!==routeVersion)return;
 let session=progress.getQuiz();
 const entry=k=>{const [id,page]=k.split(':');return {d:decks.find(d=>d.id===id),p:cache[id]?.find(p=>p.page===Number(page))}};
 if(session&&!session.pool.every(k=>entry(k).p?.question))session=null;
 main.innerHTML=`<div class="breadcrumb"><a href="#/">课程目录</a><span>/</span>自测练习</div><span class="eyebrow">RECALL BEFORE REVEAL</span><h1>先回答，再看解释</h1><p class="muted">题目对应具体课件页。练习题为本站编写，不是历年真题或正式题量预测。题目顺序、已答题数和当前答案状态会自动保存，可刷新后继续。</p><div class="toolbar"><label for="quiz-deck">范围</label><select id="quiz-deck"><option value="all">全部讲义</option>${decks.map(d=>`<option value="${d.id}">${esc(d.title)}</option>`).join('')}</select><label for="quiz-mode">内容</label><select id="quiz-mode"><option value="core">核心与补充</option><option value="all">全部自测</option><option value="weak">我的待复习</option></select><button id="start-quiz" class="primary">${session?'重新开始 20 题练习':'开始 20 题练习'}</button></div><div id="quiz-slot"><div class="empty">选择范围后开始。先口述或写下答案，再展开解释。</div></div>`;
 const save=()=>progress.saveQuiz(session);
 function show(){
  if(!session)return;
  if(session.index===session.pool.length){$('#quiz-slot').innerHTML=`<div class="study-card"><span class="eyebrow">SESSION COMPLETE</span><h2>完成 ${session.pool.length} 题 · 自评掌握 ${session.correct} 题</h2><p>本轮结果已保存。没掌握的题目已加入待复习。</p><a class="resume" href="#/review">回到待复习列表 ›</a></div>`;return}
  const {d,p}=entry(session.pool[session.index]);
  $('#quiz-slot').innerHTML=`<section class="study-card"><div class="quiz-counter">${session.index+1} / ${session.pool.length} · ${esc(d.title)} · PDF ${p.page}</div><div class="study-question">${rich(p.question.prompt)}</div><button id="reveal" class="primary" ${session.revealed?'hidden':''}>我想好了，查看答案</button><div id="quiz-answer" ${session.revealed?'':'hidden'}><div class="answer">${rich(p.question.answer)}</div><a class="resume" href="${href(d.id,p.page)}" target="_blank" rel="noopener">回看本页讲解 ↗</a><div class="score-row"><button id="know" class="primary">答对且能解释</button><button id="unknown">还没掌握</button></div></div></section>`;
  $('#reveal').onclick=()=>{session.revealed=true;save();$('#quiz-answer').hidden=false;$('#reveal').hidden=true};
  const answer=known=>{const k=key(d.id,p.page);if(known){session.correct++;if(state.weak.has(k))setMark(k,'none')}else setMark(k,'weak');session.index++;session.revealed=false;if(session.index===session.pool.length)session.finishedAt=Date.now();save();show()};
  $('#know').onclick=()=>answer(true);$('#unknown').onclick=()=>answer(false);
 }
 $('#start-quiz').onclick=()=>{
  const deck=$('#quiz-deck').value,mode=$('#quiz-mode').value;let pool=[];
  for(const d of decks){if(deck!=='all'&&d.id!==deck)continue;for(const p of cache[d.id])if(p.question&&(mode!=='core'||['core','support'].includes(p.priority))&&(mode!=='weak'||state.weak.has(key(d.id,p.page))))pool.push(key(d.id,p.page))}
  if(!pool.length){toast('该范围没有自测题；当前练习保留，可切换范围再开始。');return}
  for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}
  session={pool:pool.slice(0,20),index:0,correct:0,revealed:false,started:Date.now(),finishedAt:null,deck,mode};save();$('#start-quiz').textContent='重新开始 20 题练习';show();
 };
 if(session){$('#quiz-deck').value=session.deck;$('#quiz-mode').value=session.mode;show()}
}
function lab(id){sidebar('lab');activeDeck=null;disposeLab=renderLab(main,id)}
function progressPage(){sidebar('progress');document.title='学习进度 · CSCI 571';showProgress(main,progress,()=>{state=progress.readMarks();if(location.hash==='#/progress')sidebar('progress')})}
function syncProgress(){
 state=progress.readMarks();
 if(activeDeck){
  const k=key(activeDeck,activePage),d=decks.find(d=>d.id===activeDeck);
  const done=$('#mark-done'),weak=$('#mark-weak');
  if(done){done.textContent=state.done.has(k)?'✓ 已掌握':'标记已掌握';done.className=state.done.has(k)?'soft-button':'primary'}
  if(weak){weak.textContent=state.weak.has(k)?'◇ 已加入待复习':'加入待复习';weak.className=state.weak.has(k)?'soft-button':''}
  sidebar('reader',d,cache[activeDeck],activePage);
 }else if(location.hash==='#/progress')progressPage();
 else if(!location.hash||location.hash==='#/')home();
 else if(location.hash==='#/review')review(routeVersion);
 else if(!location.hash.startsWith('#/interpretations/'))sidebar(location.hash.split('/')[1]);
}
async function route(){
 reading?.stop();disposeLab();disposeLab=()=>{};
 const version=++routeVersion,hash=location.hash||'#/',path=hash.replace(/^#\/?/,'').split('/');
 $('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');$('#search-results').hidden=true;$('#search').value='';activeDeck=null;
 main.innerHTML='<div class="loading">正在载入…</div>';window.scrollTo({top:0,behavior:'instant'});
 try{
  if(path[0]==='interpretations'){
   if(path[1])await showInterpretation(path[1],{decks,main,side,loadDeck,navBase,isCurrent:()=>version===routeVersion});
   else{sidebar('interpretations');document.title='整体总结 · 精简版 · CSCI 571';main.innerHTML=interpretationIndex(decks);$('.interpretation-intro',main).insertAdjacentHTML('afterend',resumeBanner(progress))}
  }else if(path[0]==='deck')await reader(path[1],path[2],version);
  else if(path[0]==='review')await review(version);
  else if(path[0]==='quiz')await quiz(version);
  else if(path[0]==='lab')lab(path[1]);
  else if(path[0]==='progress')progressPage();
  else home();
  if(version!==routeVersion)return;
  const title=$('h1',main)?.textContent||document.title;
  await reading.start(hash,activeDeck?`${decks.find(d=>d.id===activeDeck).title} · P${activePage} · ${title}`:title);
 }catch(e){main.innerHTML=`<div class="empty"><h2>内容暂时未能载入</h2><p>${esc(e.message)}</p><button onclick="location.reload()">重新载入</button><p><a href="#/">返回课程目录</a></p></div>`}
}
let searchVersion=0;$('#search').addEventListener('input',async e=>{const v=++searchVersion,q=e.target.value.trim().toLowerCase(),results=$('#search-results');if(!q){results.hidden=true;return}results.hidden=false;results.innerHTML='<div class="search-count">正在搜索全部讲义…</div>';try{await loadAll()}catch{if(v===searchVersion)results.innerHTML='<div class="empty">搜索内容暂时未能载入，请稍后重新输入关键词。</div>';return}if(v!==searchVersion)return;const words=q.split(/\s+/),found=[];for(const d of decks)for(const p of cache[d.id]){const text=[d.title,d.file,p.title,p.section,p.summary,...p.explanation,...p.takeaways,p.pitfall,p.example?.code,p.question?.prompt,'p'+p.page,'第'+p.page+'页'].filter(Boolean).join(' ').toLowerCase();if(words.every(w=>text.includes(w)))found.push({d,p})}results.innerHTML=`<div class="search-count">找到 ${found.length} 页${found.length>60?' · 显示前60条，请增加关键词':''}</div>`+found.slice(0,60).map(({d,p})=>`<a class="search-item" href="${href(d.id,p.page)}"><small>${esc(d.title)} · PDF ${p.page}</small><strong>${esc(p.title)}</strong><p>${esc(p.summary.slice(0,100))}</p></a>`).join('')+(found.length?'':'<div class="empty">没有找到匹配页。试试“作用域”“子网”“CORS”或“CSS 26”。</div>')});
$('#search-results').addEventListener('click',e=>{if(e.target.closest('a')){$('#search-results').hidden=true;$('#search').value=''}});
document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap')&&!e.target.closest('#search-results'))$('#search-results').hidden=true});
$('#menu').onclick=()=>{const open=side.classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open))};
$('#close-image').onclick=()=>$('#image-dialog').close();$('#image-dialog').onclick=e=>{if(e.target===$('#image-dialog'))$('#image-dialog').close()};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='/'){e.preventDefault();$('#search').focus()}if(e.key==='Escape'){$('#search-results').hidden=true;side.classList.remove('open');$('#menu').setAttribute('aria-expanded','false')}if($('#image-dialog').open)return;if(activeDeck&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){const d=decks.find(x=>x.id===activeDeck),next=activePage+(e.key==='ArrowRight'?1:-1);if(next>=1&&next<=d.count){e.preventDefault();location.hash=href(activeDeck,next)}}});
$('.skip').onclick=e=>{e.preventDefault();main.focus();main.scrollIntoView({block:'start'})};
window.addEventListener('hashchange',route);
try{decks=await fetchJSON('content/decks.json');progress=createProgressStore({decks,labIds:labs.map(lab=>lab.id),onError:storageProblem});state=progress.readMarks();reading=createReadingTracker(progress,main);window.addEventListener('storage',event=>{if(event.key?.startsWith(PROGRESS_PREFIX+'mark:')||['571-done','571-weak'].includes(event.key))syncProgress()});window.addEventListener('pageshow',event=>{if(event.persisted)syncProgress()});await route();loadAll().catch(()=>{})}catch(e){main.innerHTML=`<div class="empty">${esc(e.message)}<p>请刷新重试。</p></div>`}
