const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rich = value => esc(value).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const loaded = new Map();
const kinds = {concept:'概念串讲',background:'背景理解',history:'发展历史 · 可跳过',admin:'阅读与课程安排'};
export const interpretationHref = id => `#/interpretations${id?'/'+id:''}`;
export async function getInterpretation(id){
 if(!loaded.has(id))loaded.set(id,fetch(`content/interpretations/${id}.json`).then(r=>{if(!r.ok)throw new Error('整体总结暂时未能载入，请刷新重试。');return r.json()}).catch(e=>{loaded.delete(id);throw e}));
 return loaded.get(id);
}
const historyNotice = () => `<aside class="history-guidance"><strong>教授补充：发展历史无需复习或记忆</strong><p lang="en">Development &quot;history&quot; is not something that you have to recall or read again.</p><span>总结中已将发展历史单独标为可跳过。涉及语言规则、协议行为和技术原理的内容仍然讲解；产业统计与产品案例另标为背景。</span></aside>`;
function pageRanges(pages){const sorted=[...pages].sort((a,b)=>a-b),parts=[];for(let i=0;i<sorted.length;i++){let start=sorted[i],end=start;while(sorted[i+1]===end+1)end=sorted[++i];parts.push(start===end?String(start):`${start}–${end}`)}return parts.join('、')}
export function interpretationIndex(decks){
 return `<div class="breadcrumb"><a href="#/">课程目录</a><span>/</span>整体总结</div><span class="eyebrow">SLIDES INTERPRETATION</span><h1>整体总结与串讲</h1><p class="interpretation-intro">把一份课件的知识连起来理解。先掌握主线，再用代码和例子补齐基础，随时回到对应原页。</p>${historyNotice()}<div class="section-top"><div><h2>选择一份课件</h2><p>13 份讲义 + syllabus · 对应全部 816 页</p></div></div><div class="interpretation-index">${decks.map((d,i)=>`<a href="${interpretationHref(d.id)}"><span class="course-index">${String(i+1).padStart(2,'0')}</span><div><h2>${esc(d.title)}</h2><p>${esc(d.description)}</p><small>覆盖 PDF 1–${d.count} 页</small></div><span class="interpretation-arrow" aria-hidden="true">↗</span></a>`).join('')}</div>`;
}
export async function showInterpretation(id,{decks,main,side,loadDeck,navBase,isCurrent}){
 const deck=decks.find(d=>d.id===id);if(!deck)throw new Error('没有找到这份讲义。');
 const [summary,pages]=await Promise.all([getInterpretation(id),loadDeck(id)]);if(!isCurrent())return;
 document.title=`${deck.title} · 整体总结与串讲 · CSCI 571`;
 side.innerHTML=navBase('interpretations')+`<label class="side-heading" for="interpretation-select">切换整体总结</label><select class="course-select" id="interpretation-select">${decks.map(d=>`<option value="${d.id}" ${d.id===id?'selected':''}>${esc(d.title)}</option>`).join('')}</select><nav class="interpretation-toc" aria-label="总结章节"><button data-scroll="interpretation-start">本讲主线与学习目标</button>${summary.sections.map((s,i)=>`<button data-scroll="interpretation-section-${i}" class="${s.kind==='history'?'history-toc':''}"><small>${String(i+1).padStart(2,'0')}${s.kind==='history'?' · 可跳过':''}</small>${esc(s.title)}</button>`).join('')}<button data-scroll="interpretation-checklist">考前自查</button></nav><a href="#/deck/${id}/${id==='web'?51:1}" class="side-back">打开原有逐页讲解 ›</a>`;
 side.scrollTop=0;
 side.querySelector('#interpretation-select').onchange=e=>location.hash=interpretationHref(e.target.value);
 const pageMap=new Map();summary.sections.forEach((s,i)=>s.pages.forEach(page=>pageMap.set(page,{s,i})));
 const refs=section=>`<details class="interpretation-refs"><summary>对应课件：PDF ${pageRanges(section.pages)}（${section.pages.length} 页）</summary><div class="interpretation-page-links">${section.pages.map(n=>`<a href="#/deck/${id}/${n}" title="${esc(pages[n-1].title)}"><span>P${n}</span>${esc(pages[n-1].title)}</a>`).join('')}</div></details>`;
 const body=section=>`${section.paragraphs.map(p=>`<p>${rich(p)}</p>`).join('')}${section.example?`<div class="code-box"><div class="code-toolbar"><span>${esc(section.example.lang).toUpperCase()} · 串讲示例</span></div><pre><code>${esc(section.example.code)}</code></pre></div><p class="example-note">${rich(section.example.explanation)}</p>`:''}<ul class="interpretation-points">${section.takeaways.map(p=>`<li>${rich(p)}</li>`).join('')}</ul>${refs(section)}`;
 const index=decks.findIndex(d=>d.id===id);
 main.innerHTML=`<article class="interpretation" id="interpretation-start"><div class="breadcrumb"><a href="#/">课程目录</a><span>/</span><a href="#/interpretations">整体总结</a><span>/</span>${esc(deck.title)}</div><span class="eyebrow">SLIDES INTERPRETATION · ${deck.count} PAGES</span><h1>${esc(summary.title)}</h1><p class="interpretation-intro">${rich(summary.intro)}</p><div class="interpretation-actions"><a href="#/deck/${id}/${id==='web'?51:1}" class="summary-open-original">打开原有逐页讲解 ↗</a><button id="print-interpretation">打印整体总结</button></div>${historyNotice()}${id==='ai'?'<div class="notice">AI Basics 的完整考试范围仍需以教师说明为准；本篇提供完整理解，不预测考试范围。</div>':''}<section class="interpretation-goals"><span class="block-label">读完后，你应该能够</span><ul>${summary.goals.map(g=>`<li>${rich(g)}</li>`).join('')}</ul></section><details class="interpretation-coverage"><summary>全页覆盖对照 · ${pageMap.size} / ${deck.count} 页</summary><p>每页均对应下方一个串讲章节。发展历史单独标记，保留页码供你确认范围。</p><div class="coverage-grid">${pages.map(p=>{const match=pageMap.get(p.page);return `<a href="#/deck/${id}/${p.page}" class="${match?.s.kind==='history'?'coverage-history':''}" title="${esc(p.title)} → ${esc(match?.s.title)}">P${p.page}${match?.s.kind==='history'?'<span>历史 · 跳过</span>':`<span>${esc(kinds[match?.s.kind]||'')}</span>`}</a>`}).join('')}</div></details><div class="interpretation-sections">${summary.sections.map((s,i)=>s.kind==='history'?`<details class="interpretation-history" id="interpretation-section-${i}"><summary><span class="interpretation-kind">${String(i+1).padStart(2,'0')} · 发展历史 / 可跳过</span><strong>${esc(s.title)}</strong><small>PDF ${pageRanges(s.pages)}</small></summary><div class="interpretation-history-body">${body(s)}</div></details>`:`<section class="interpretation-section" id="interpretation-section-${i}"><span class="interpretation-kind ${s.kind}">${String(i+1).padStart(2,'0')} · ${kinds[s.kind]}</span><h2>${esc(s.title)}</h2>${body(s)}</section>`).join('')}</div><section class="interpretation-connections"><span class="block-label">把这一讲接到其他知识上</span>${summary.connections.map(p=>`<p>${rich(p)}</p>`).join('')}</section><section class="interpretation-checklist" id="interpretation-checklist"><h2>考前自查</h2><p class="muted">先独立回答，再回到对应讲解核对；发展历史不列入记忆任务。</p><ol>${summary.examChecklist.map(p=>`<li>${rich(p)}</li>`).join('')}</ol></section><nav class="pager" aria-label="其他讲义总结">${index>0?`<a href="${interpretationHref(decks[index-1].id)}"><small>上一份整体总结</small>${esc(decks[index-1].title)}</a>`:'<span></span>'}${index<decks.length-1?`<a href="${interpretationHref(decks[index+1].id)}"><small>下一份整体总结</small>${esc(decks[index+1].title)}</a>`:'<a href="#/interpretations">返回总结目录</a>'}</nav><footer>依据原课件逐组串讲 · 页码按 PDF 阅读器页序<br>逐页正文、原图、示例与自测完整保留；发展历史按教授补充安排。</footer></article>`;
 main.querySelector('#print-interpretation').onclick=()=>window.print();
 side.querySelectorAll('[data-scroll]').forEach(button=>button.onclick=()=>{const target=main.querySelector('#'+button.dataset.scroll);if(!target)return;if(target.tagName==='DETAILS')target.open=true;target.scrollIntoView({block:'start',behavior:'smooth'});side.classList.remove('open');document.querySelector('#menu').setAttribute('aria-expanded','false')});
}
export function interpretationBanner(id){return `<div class="interpretation-reader-entry"><a href="${interpretationHref(id)}">本讲整体总结与串讲 <span aria-hidden="true">→</span></a><p class="reader-history-update" hidden></p></div>`}
export async function markHistoricalPage(id,page,{main,isCurrent}){
 try{const summary=await getInterpretation(id);if(!isCurrent())return;const section=summary.sections.find(s=>s.pages.includes(page));if(section?.kind==='history'){const note=main.querySelector('.reader-history-update');if(note){note.hidden=false;note.textContent='教授最新说明：本页属于发展历史，无需重读或记忆。请以此说明安排复习；原页中的历史记忆建议不再适用。'}}}catch{/* Existing per-slide reading remains usable if the new supplement is unavailable. */}
}
